(in-package #:org.shirakumo.random-sampling)

(random-state:define-generator hammersley-2 32 (random-state:hash-generator)
    ((leap (make-array 2 :element-type '(unsigned-byte 32) :initial-element 1) :type (simple-array (unsigned-byte 32) (2))))
  (:copy
   (make-hammersley-2 :%seed (hammersley-2-%seed generator)
                      :index (hammersley-2-index generator)
                      :leap (make-array 2 :element-type '(unsigned-byte 32) :initial-contents (hammersley-2-leap generator))))
  (:hash
   (flet ((dim (base leap seed)
            (let ((seed2 (+ seed (* index leap)))
                  (base-inv (float (/ base) 0f0))
                  (r 0.0))
              (loop while (/= 0 seed2)
                    do (incf r (* (mod seed2 base) base-inv))
                       (setf base-inv (/ base-inv base))
                       (setf seed2 (/ seed2 base))
                    finally (return r)))))
     (vec (dim 2 (aref leap 0) (ldb (byte 32 0) seed))
          (dim 3 (aref leap 1) (ldb (byte 32 32) seed))))))

(random-state:define-generator hammersley-3 32 (random-state:hash-generator)
    ((leap (make-array 3 :element-type '(unsigned-byte 32) :initial-element 1) :type (simple-array (unsigned-byte 32) (3))))
  (:copy
   (make-hammersley-3 :%seed (hammersley-3-%seed generator)
                      :index (hammersley-3-index generator)
                      :leap (make-array 3 :element-type '(unsigned-byte 32) :initial-contents (hammersley-3-leap generator))))
  (:hash
   (flet ((dim (base leap seed)
            (let ((seed2 (+ seed (* index leap)))
                  (base-inv (float (/ base) 0f0))
                  (r 0.0))
              (loop while (/= 0 seed2)
                    do (incf r (* (mod seed2 base) base-inv))
                       (setf base-inv (/ base-inv base))
                       (setf seed2 (/ seed2 base))
                    finally (return r)))))
     (vec (dim 2 (aref leap 0) (ldb (byte 16 0) seed))
          (dim 3 (aref leap 1) (ldb (byte 16 16) seed))
          (dim 5 (aref leap 2) (ldb (byte 16 32) seed))))))
